services:

    Jett\JSONEntitySerializerBundle\Service\Serializer:
        public: true
        arguments:
            - '@Jett\JSONEntitySerializerBundle\Service\ClassGenerator'

    entity_serializer:
        alias:  Jett\JSONEntitySerializerBundle\Service\Serializer
        public: true

    Jett\JSONEntitySerializerBundle\Annotation\AnnotationHelper:
        arguments:
            - '@annotation_reader'
            - '@Jett\JSONEntitySerializerBundle\Service\ConfigService'

    Jett\JSONEntitySerializerBundle\Info\InfoProvider:
        arguments:
            - '@Jett\JSONEntitySerializerBundle\Annotation\AnnotationHelper'
            - '@Jett\JSONEntitySerializerBundle\Service\ConfigService'
            - '@doctrine.orm.entity_manager'

    Jett\JSONEntitySerializerBundle\Service\ClassGenerator:
        arguments:
            - '@Jett\JSONEntitySerializerBundle\Info\InfoProvider'
            - '@Jett\JSONEntitySerializerBundle\Service\ConfigService'
            - '%kernel.cache_dir%/serializer'
            - '%kernel.environment%'

    Jett\JSONEntitySerializerBundle\Service\CacheWarmer:
        arguments:
            - '@Jett\JSONEntitySerializerBundle\Service\ClassGenerator'
        tags:
            - kernel.cache_warmer

