services:

    Jett\JSONEntitySerializerBundle\Service\Serializer:
        public: true
        arguments:
            - '@Jett\JSONEntitySerializerBundle\Service\SerializerBuilder'

    entity_serializer:
        alias:  Jett\JSONEntitySerializerBundle\Service\Serializer
        public: true

    Jett\JSONEntitySerializerBundle\Service\SerializerBuilder:
        arguments:
            - '@annotation_reader'
            - '@Jett\JSONEntitySerializerBundle\Service\ConfigService'
            - '@doctrine.orm.entity_manager'
            - '%kernel.cache_dir%/serializer'
            - '%kernel.environment%'

    Jett\JSONEntitySerializerBundle\Service\CacheWarmer:
        arguments:
            - '@Jett\JSONEntitySerializerBundle\Service\SerializerBuilder'
        tags:
            - kernel.cache_warmer

    Jett\JSONEntitySerializerBundle\Transformer\Common\:
        resource: '../../Transformer/Common/'
        tags:
            - entity_serializer.transformer